DROP TABLE IF EXISTS BC_DEVICE_CLASS;
CREATE TABLE BC_DEVICE_CLASS(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    NAME VARCHAR(90)    COMMENT '名称' ,
    CODE VARCHAR(90)    COMMENT '代码' ,
    F_ID INT    COMMENT '父类ID' ,
    REMARK VARCHAR(255)    COMMENT '备注' ,
    LEVEL INT    COMMENT '级别' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '设备类型表';

DROP TABLE IF EXISTS ACT_DEVICE_COUNT;
CREATE TABLE ACT_DEVICE_COUNT(
    CLASS_ID INT NOT NULL AUTO_INCREMENT  COMMENT '设备类型ID' ,
    COUNT INT    COMMENT '数量' ,
    CREATED_BY INT    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY INT    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (CLASS_ID)
)  COMMENT = '设备数量表';

DROP TABLE IF EXISTS ACT_DEVICE_DETAIL;
CREATE TABLE ACT_DEVICE_DETAIL(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    MODEL VARCHAR(255)    COMMENT '设备型号' ,
    CLASS_ID INT    COMMENT '设备分类ID' ,
    NAME VARCHAR(32)    COMMENT '名称' ,
    SN VARCHAR(90)    COMMENT '序列号' ,
    STATUS INT    COMMENT '设备状态(1:正常；0:已经报废)' ,
    INVENTOR_STATUS INT    COMMENT '库存状态(1:在库；0:不在库)' ,
    ADDRESS_ID INT    COMMENT '当前位置ID' ,
    ADDRESS VARCHAR(255)    COMMENT '当前位置名称' ,
    RF_CODE VARCHAR(255)    COMMENT 'RFID编码（二维码编码）' ,
    BUY_TIME VARCHAR(255)    COMMENT '购买时间' ,
    FACTORY VARCHAR(255)    COMMENT '制造商' ,
    MANUFACTURE_TIME VARCHAR(255)    COMMENT '制造日期' ,
    REMARK VARCHAR(255)    COMMENT '备注' ,
    CREATED_BY INT    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY INT    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    EFFECTIVE_TIME INT    COMMENT '保质期(天)' ,
    PRIMARY KEY (ID)
)  COMMENT = '设备明细表';

DROP TABLE IF EXISTS ACT_DEVICE_LOCATION_LOG;
CREATE TABLE ACT_DEVICE_LOCATION_LOG(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '位置历史表ID' ,
    DEVICE_ID INT    COMMENT '设备ID' ,
    LOCATION_ID INT    COMMENT '位置ID' ,
    LOCATION_NAME VARCHAR(90)    COMMENT '位置名称' ,
    CREATED_BY INT    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '设备历史位置记录';

DROP TABLE IF EXISTS ACT_DOC;
CREATE TABLE ACT_DOC(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '单据ID' ,
    NAME VARCHAR(32)    COMMENT '单据名称' ,
    CODE VARCHAR(90)    COMMENT '单据编码' ,
    DOC_TYPE INT    COMMENT '单据类型(0:采购单;1:报废单;2:出库单;3:盘点单)' ,
    LOCATION_ID INT    COMMENT '关联的位置ID' ,
    REMARK VARCHAR(255)    COMMENT '备注' ,
    CREATED_BY INT    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY INT    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '单据表';

DROP TABLE IF EXISTS ACT_DOC_DEVICE;
CREATE TABLE ACT_DOC_DEVICE(
    DOC_ID INT NOT NULL   COMMENT '单据ID' ,
    DEVICE_ID INT NOT NULL   COMMENT '设备ID' ,
    STAT INT    COMMENT '单据中的设备状态(0:未确认;1:已确认)' ,
    PRIMARY KEY (DOC_ID,DEVICE_ID)
)  COMMENT = '单据设备关系表';

DROP TABLE IF EXISTS BC_USER;
CREATE TABLE BC_USER(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    USERNAME VARCHAR(255) NOT NULL   COMMENT '用户名' ,
    PASSWORD VARCHAR(90)    COMMENT '密码' ,
    ROLE INT    COMMENT '角色' ,
    STATE INT    COMMENT '状态（0:不可用;1:可用;）' ,
    PRIMARY KEY (ID)
)  COMMENT = '用户表';

DROP TABLE IF EXISTS BC_LOCATION;
CREATE TABLE BC_LOCATION(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '位置ID' ,
    NAME VARCHAR(32)    COMMENT '位置名称' ,
    CODE VARCHAR(90)    COMMENT '位置代码' ,
    CREATED_BY INT    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '位置信息表';

DROP TABLE IF EXISTS BC_ROLE;
CREATE TABLE BC_ROLE(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    NAME VARCHAR(32)    COMMENT '名称' ,
    CREATED_BY INT    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '角色表';

DROP TABLE IF EXISTS BC_POWER;
CREATE TABLE BC_POWER(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT 'ID' ,
    NAME VARCHAR(32)    COMMENT '名称' ,
    LINK VARCHAR(90)    COMMENT '代码' ,
    F_ID VARCHAR(255)    COMMENT '父权限ID' ,
    PRIMARY KEY (ID)
)  COMMENT = '权限表';

DROP TABLE IF EXISTS BC_ROLE_POWER;
CREATE TABLE BC_ROLE_POWER(
    ROLE_ID INT NOT NULL   COMMENT '角色ID' ,
    POWER_ID INT NOT NULL   COMMENT '权限ID' ,
    IS_SELECT INT    COMMENT '允许查询' ,
    IS_UPDATE INT    COMMENT '允许修改' ,
    IS_DELETE INT    COMMENT '允许删除' ,
    IS_CREATE INT    COMMENT '允许新建' ,
    RESERVE1 INT    COMMENT '备用1' ,
    RESERVE2 INT    COMMENT '备用2' ,
    CREATED_BY INT    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    PRIMARY KEY (ROLE_ID,POWER_ID)
)  COMMENT = '角色权限表';

DROP TABLE IF EXISTS ACT_DEVICE_REPAIR;
CREATE TABLE ACT_DEVICE_REPAIR(
    ID INT NOT NULL AUTO_INCREMENT  COMMENT '检修记录ID' ,
    DEVICE_ID INT NOT NULL   COMMENT '设备ID' ,
    REPAIR_TYPE INT   DEFAULT 0 COMMENT '检修类别;0：维修；1：检修' ,
    STAT INT    COMMENT '检修状态;0：送检；1：检修完毕' ,
    REPAIR_RESULT VARCHAR(255)    COMMENT '检修/维修结果' ,
    REPAIR_USER VARCHAR(255)    COMMENT '检修人' ,
    REPAIR_CREATE_USER VARCHAR(255)    COMMENT '送修人' ,
    REMARK VARCHAR(255)    COMMENT '检修备注' ,
    BEGIN_TIME DATETIME    COMMENT '开始检修时间' ,
    END_TIME DATETIME    COMMENT '结束检修时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '设备检修维修记录';

