server:
  port: 8888
spring:
  mvc:
    pathmatch:
      ##为了解决swagger 3.0.0 版本与spring boot 2.6.4版本不兼容增加的
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.18.134:3306/device_management?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=true
    username: chsb
    password: Lzyw1234
    initialize: false
    initialization-mode: never
    schema: classpath:db/schema.sql
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
logging:
  #指定logback.xml配置文件的路径
  config: classpath:log/logback.xml