global using Nacos.V2;
global using Nacos.V2.Naming.Event;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
global using Microsoft.Extensions.Configuration;
global using Nacos.AspNetCore.V2;
global using zy.webcore.Share.Constraint.Core.Interfaces;